### PR TITLE
Add distribution board PCB

### PR DESCRIPTION
**Pull request by EiNSTeiN-**
This is a PCB that can be used to connect the canbus cables together at the distribution box. I made it to fit in the recess that is available in the distribution box. I produced one on my CNC as a test but also ordered a few from PCBWay to make sure they can be produced correctly, as I'm fairly beginner at making PCBs.

Screen Shot 2023-05-31 at 11 14 14 AM

### CODE REVIEW

**Comment by viesturz** [comment]
One concern is that it will need to handle ~12 amps peak. And the trackes might not be thick enough for that.

**Comment by AugieSpear** [comment]
If you're going to have a power distribution board, you're going to need at least one power input every 2-3 toolheads. You will also have to heat them up one at a time. I am going to use 5 rapido hotends so this might be tough.

**Comment by AugieSpear** [comment]
I'd recommend using screw terminals instead of jst connectors for the power because they can support higher current and would probably be safer.

**Comment by EiNSTeiN-** [comment]
Screw terminals aren't a bad idea, I went with JST since that is what I have on hand and can be easily purchased. The JST-XH pins should be rated for 3 amps which is fine for a regular heater with room for the motor. But I agree it'll be a problem with 5 extruders powering at the same time.

Another thought, I think the distribution box needs to be reworked so it can stay in place while we work on the wiring inside. The current approach of "sandwiching" the printer's back panel from 2 sides is a little difficult to work around especially for 350mm printers!

**Comment by EiNSTeiN-** [comment]
What would you think of [this type of terminal](https://vi.aliexpress.com/item/1005002951702737.html?spm=a2g0o.productlist.main.25.6e3211931JcE8W&algo_pvid=5cfad59b-a04f-4bf5-a2bd-50cb518424f2&algo_exp_id=5cfad59b-a04f-4bf5-a2bd-50cb518424f2-12&pdp_npi=3%40dis%21CAD%211.18%210.92%21%21%21%21%21%4021021d7b16857106829158907d0786%2112000022933125606%21sea%21CA%21909218285&curPageLogUid=OhetneQVtmKX) so the toolheads can easily be disconnected when needed?

I could re-make this board with a 2-pin 5.08mm terminals for the power input, 2-pin 3.5mm terminals for each toolhead, and regular 2.54mm terminals for canbus communication. That should provide >15A for input and >5A output per toolhead.

I would rather go with 4-pin terminals to simplify the BOM but that would require adding more space to the distribution box to accommodate a larger PCB.

**Comment by AugieSpear** [comment]
For each toolhead I was thinking of a 2.54mm screw terminal like [this](https://www.aliexpress.us/item/3256804493653141.html?spm=a2g0o.productlist.main.3.21ec64ccmbcrTA&algo_pvid=1556db4a-563a-4f5f-98a4-c7c00ed85aff&algo_exp_id=1556db4a-563a-4f5f-98a4-c7c00ed85aff-1&pdp_npi=3%40dis%21USD%212.46%211.48%21%21%21%21%21%402102172f16857295129078190d075c%2112000030077142902%21sea%21US%210&curPageLogUid=71iuMa43zjV1) should be fine. It's rated for 6 amps and should be fine up to around 130-140 watts. For the Main power connector two 5mm pitch screw terminals would work because the max power I am going to use for all hotends is around 400 watts (16 amps at 24v). The reason I wouldn't go for the quick release is because of the added cost. They're about 50% more expensive per one (21 cents vs. 15 cents). It isn't a big deal on cost but it is still there and only for one component. I would also try and integrate a Canbus to USB converter into the distribution board so we can make setup simpler.

**Comment by EiNSTeiN-** [comment]
I ordered some parts, they will take a couple weeks to get here before I can update and test the PCB.

**Comment by viesturz** [comment]
I'm using screw terminals on a PCB with the main cable soldered in place.

IMO the wiring at the back is quite permanent, have not touched mine for
a while. For servicing, I just unplug the hotend.

Viesturs

**Comment by viesturz** [comment]
Integrating U2C is an option. I have it in the electronics box. Probably a
bit easier to service there.

Also some people may choose to use MCU integrated Can. My experience with
that is bit great however.

I don't have strong opinions about the box, happy to merge whatever looks
half decent :)

**Pull request merged**
