### PR TITLE
Add 3.4mm thickness to the shuttle

### PR DESCRIPTION
**Pull request by EiNSTeiN-**
As suggested in #2 this change makes the shuttle 3.4mm thicker to allow using BHCS screws with a ball end Allen key instead of pan slotted screws. In my opinion it's much more common hardware and after having screws/unscrewed the shuttle a few times already, I can say it's a lot more convenient! I updated the BOM, the assembly instructions and some of the pictures. After installing this the dock Y offsets will need to be adjusted by 3.4mm.

I assembled this on a spare rail to test and take photos, I have a print currently running to I'll be able to assemble on my actual printer soon. I only updated the `Lowered3mm` STL since that's what the CAD currently contains.

We can see there's plenty of clearance for the Allen key:
image

### CODE REVIEW

**Comment by viesturz** [comment]
Nice, thanks for working on this.

A few asks before merging:

- please keep the old STL around for now, add -flathead?
- the screw holes for the mgn9 are super deep now, moving to 8mm screws and shallower holes should help with rigidity.
- the belts clipped inside the hooks are almost touching the hotend when changing. New there is singnificantly more room to work with, if you can add a ~1-2mm groove for the belts.

**Comment by EiNSTeiN-** [comment]
> the screw holes for the mgn9 are super deep now, moving to 8mm screws and shallower holes should help with rigidity.

One argument in favor of keeping 6mm BHCS, those are the same as the standard Voron Tap BOM, so people upgrading from an existing build will already have them, or can just source a regular voron tap kit from a local vendor and have everything they need.

The 8mm SHCS screws seem to be quite common too (I had a bunch extra in my voron kit) so I could see using those, but the allen key size is larger on the SHCS than the BHCS screws. They would only work on the MGN9 side due to the clearance issue on the MGN12 side.

What do you think?

**Comment by EiNSTeiN-** [comment]
I added the belt slots and also modified the endstop to accommodate for the deeper holes (leaving the screw holes for now until I hear back)

**Comment by viesturz** [comment]
Looking good, just need to update the screw holes.

**Comment by EiNSTeiN-** [comment]
Regarding my questions above, are you OK with keeping the BHCS 6mm on the side where the screw holes overlap the carriage, and go with SHCS 8mm on the other side? I think it's best to stick with hardware people will already have from their Voron Tap kit. Plus there's no rigidity issues with Voron Tap which uses 6mm screws too.

**Comment by EiNSTeiN-** [comment]
I went ahead and added a 8mm option along with the 6mm option, people who have the voron tap kit and want to use the standard hardware can use the 6mm version, and those who have 8mm screws in stock can use that more rigid version (I don't, so I can't test that version), hope that works for everyone :)

I made the cad parametric so there is now an option for adjusting the carriage holes to any length (in practice 6, 8 and 10 should work). The XEndstop part also adjusts automatically for the screw length. Hope the new folder structure makes sense as well.

**Comment by viesturz** [comment]
Nice work, merging. Thanks for the folder cleanup!

**Pull request merged**
